import java.text.SimpleDateFormat
pipeline {
    agent any
    
    stages {
        stage('Prepare Today Date') {
            steps {
                 script {
                    def dateFormat = new SimpleDateFormat("yyyy-MM-dd")
                    def date = new Date()
                
                    env.TODAY = dateFormat.format(date)                
                    
                }                
            } 
        }
        stage('Print Today Date') {
            steps {
                  echo "REST API!"
            } 
        }
}
}
